language: node_js
node_js:
  - "lts/*"
script:
  - npm install -g eslint
  - eslint ./**/*.js
  - npm install -g documentation
  - documentation build TeamSpeak3.js property/**.js --project-name "TS3-NodeJS-Library" -f html -o docs
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: docs
  on:
    branch: master
