language: node_js
node_js:
  - "lts/*"
services:
  - docker
before_install:
  - docker pull teamspeak
  - docker run -d --name=teamspeak -p 10011:10011/tcp -p 10022:10022/tcp -p 30033:30033/tcp -e TS3SERVER_LICENSE=accept -e TS3SERVER_QUERY_PROTOCOLS=raw,ssh teamspeak ts3server serveradmin_password=abc123
before_script:
  - npm install -g eslint documentation
script:
  - npm run eslint
  - npm test
  - nyc report --reporter=text-lcov | coveralls
  - npm run generate-docs
after_script:
  - docker stop teamspeak
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: docs
  on:
    branch: master